
export enum UserRole {
  EMPLOYEE = 'EMPLOYEE',
  ADMIN = 'ADMIN',
  RESTAURANT_MANAGER = 'RESTAURANT_MANAGER',
  HR_MANAGER = 'HR_MANAGER',
  BUSINESS_OWNER = 'BUSINESS_OWNER',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
  MARKETING_MANAGER = 'MARKETING_MANAGER',
  SUPER_ADMIN = 'SUPER_ADMIN'
}

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  LATE = 'LATE',
  ABSENT = 'ABSENT',
  LEFT_EARLY = 'LEFT_EARLY'
}

export enum LeaveType {
  SICK = 'SICK',
  ANNUAL = 'ANNUAL',
  OTHER = 'OTHER'
}

export enum LeaveStatus {
  PENDING_MANAGER = 'PENDING_MANAGER',
  PENDING_HR = 'PENDING_HR',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED'
}

export enum EmployeeArea {
  FOH = 'FOH',
  BOH = 'BOH',
  MANAGEMENT = 'MANAGEMENT'
}

// --- SHIFT SCHEDULING TYPES ---

export enum ShiftType {
  OFF = 'OFF',       // Libur (RED)
  MORNING = 'MORNING', // Shift Pagi (BLUE)
  MIDDLE = 'MIDDLE'   // Shift Middle (GREEN)
}

export interface ShiftDefinition {
  id: string;
  code: ShiftType;
  name: string;
  defaultStartTime: string;
  defaultEndTime: string; // or empty string for OFF
  color: string;
}

export type ShiftPlanStatus = 'DRAFT' | 'PUBLISHED';

export interface MonthlyShiftPlan {
  id: string;
  outletId: string;
  month: number;
  year: number;
  status: ShiftPlanStatus;
  createdByManagerId: string;
  createdAt: string;
  updatedAt: string;
}

export interface ShiftAssignment {
  id: string;
  planId?: string; // Optional link to parent plan
  employeeId: string;
  date: string; // YYYY-MM-DD
  type: ShiftType;
  startTime: string; // HH:mm
  endTime: string; // HH:mm
  color: string; // Hex Code
  isPublished: boolean;

  // Audit fields
  createdByManagerId?: string;
  createdAt?: string;
  updatedAt?: string;
}

export const SHIFT_COLORS = {
  [ShiftType.OFF]: '#EF4444',    // Red-500
  [ShiftType.MORNING]: '#3B82F6', // Blue-500
  [ShiftType.MIDDLE]: '#22C55E'   // Green-500
};

export enum EmploymentCategory {
  PERMANENT = 'PERMANENT', // Tetap
  PROBATION = 'PROBATION', // Percobaan
  DAILY_WORKER = 'DAILY_WORKER' // Harian
}

export interface Employee {
  id: string; // Smart ID: [STATUS]-[DEPT]-[YEAR][SEQ]
  name: string;
  email: string;
  phone?: string;
  pin?: string; // Added PIN for security
  address?: string;
  role: UserRole;
  department: string;
  area: EmployeeArea;
  category: EmploymentCategory; // New field
  joinedDate: string; // YYYY-MM-DD
  avatarUrl?: string;
  birthDate?: string; // YYYY-MM-DD
  isActive: boolean; // Default true
  deactivationDate?: string; // YYYY-MM-DD
  deactivationReason?: string;
}

export interface WorkSchedule {
  shiftName: string;
  startTime: string;
  endTime: string;
}

export interface AttendanceLog {
  id: string;
  employeeId: string;
  date: string; // YYYY-MM-DD
  checkInTime: string;
  checkOutTime?: string;
  status: AttendanceStatus;
  latitude: number;
  longitude: number;
  photoInUrl?: string;
  notes?: string;
  correctionNote?: string;
}

export interface LeaveRequest {
  id: string;
  employeeId: string;
  type: LeaveType;
  startDate: string;
  endDate: string;
  reason: string;
  status: LeaveStatus;
}

export interface ApiResponse<T> {
  success: boolean;
  message: string;
  data?: T;
}

// --- PERFORMANCE MODULE TYPES ---

export type ChecklistCategory = 'UMUM' | 'KHUSUS';

export interface ChecklistItemDef {
  key: string;
  label: string;
  description: string;
  category: ChecklistCategory;
}

export interface ChecklistItemResult {
  checked: boolean;
  score: number; // 1-5
  notes: string;
}

export interface ChecklistSummary {
  totalScoreUmum: number;
  avgScoreUmum: number;
  totalScoreKhusus: number;
  avgScoreKhusus: number;
  totalScoreAll: number;
  avgScoreAll: number;
  overallComment: string;
}

export interface DailyChecklistData {
  items: Record<string, ChecklistItemResult>; // Keyed by ChecklistItemDef.key
  summary: ChecklistSummary;
  isFinalized: boolean;
}

export interface DailyPerformanceSnapshot {
  id: string;
  employeeId: string;
  attendanceLogId: string;
  date: string; // YYYY-MM-DD
  area: EmployeeArea;
  punctualityScore: number;
  checklistScores?: Record<string, number>;
  dailyChecklist?: DailyChecklistData;
  presenceStatus: AttendanceStatus;
  autoGenerated: boolean;
  status: 'AUTO_GENERATED' | 'REVIEWED' | 'FINALIZED';
  summaryComment?: string;
}

export interface PerformanceReview {
  id: string;
  employeeId: string;
  reviewerId: string;
  periodMonth: number;
  periodYear: number;
  area: EmployeeArea;
  scores: Record<string, number>;
  notes: Record<string, string>;
  overallScore: number;
  overallComment: string;
  isFinalized: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface PerformanceIndicator {
  key: string;
  label: string;
  category: EmployeeArea;
}

export interface EmployeeOfTheMonth {
  employeeId: string;
  name: string;
  department: string;
  avatarUrl?: string;
  periodMonth: number;
  periodYear: number;
  avgScore: number;
  achievementBadge: string; // "Top Performer", "Star Employee"
  description: string;
}

// --- JOBDESK TYPES (TASK LIST) ---

export interface JobdeskTask {
  id: string;
  label: string;
}

export interface JobdeskSubmission {
  id: string;
  employeeId: string;
  date: string; // YYYY-MM-DD
  area: EmployeeArea;
  completedTaskIds: string[]; // Array of task IDs that are checked
  lastUpdated: string;
  managerNote?: string; // Feedback from manager
}

// --- PAYROLL / PAYSLIP MODULE TYPES ---

export type PayslipStatus = 'DRAFT' | 'READY_TO_SEND' | 'SENT' | 'CANCELLED';

export interface Payslip {
  id: string;
  employeeId: string;
  periodMonth: number;
  periodYear: number;
  payDate: string; // ISO Date

  // Earnings
  basicSalary: number;
  allowanceMeal: number;
  allowanceTransport: number;
  allowanceOther: number;
  overtimeHours: number;
  overtimeAmount: number;
  bonus: number; // Performance based
  commission: number;

  // Deductions
  bpjsKesehatan: number;
  bpjsKetenagakerjaan: number;
  taxPPh21: number;
  otherDeductions: number; // Late fines, cash advance (kasbon)

  // Totals
  totalEarnings: number;
  totalDeductions: number;
  netSalary: number;

  // Meta
  status: PayslipStatus;
  isVisibleToEmployee: boolean;
  notesForEmployee?: string;
  notesInternalHr?: string;
  createdByHrId: string;
  verifiedByFinanceId?: string;
  createdAt: string;
  updatedAt: string;
}


// --- MANAGER SPECIFIC TYPES ---

export interface PerformanceRecord {
  id: string;
  employeeId: string;
  date: string;
  type: 'SP1' | 'SP2' | 'SP3' | 'COACHING';
  description: string;
}

export interface Transaction {
  id: string;
  date: string;
  desc: string;
  amount: number;
  type: 'IN' | 'OUT';
  outlet: string;
}

export interface OperationalReport {
  id: string;
  date: string;
  salesTotal: number;
  customerCount: number;
  notes: string;
}

// Legacy simple type for Finance Panel input (retained for backward compatibility if needed)
export interface PayrollEntry {
  id: string;
  employeeId: string;
  month: number;
  year: number;
  overtimeHours: number;
  bonus: number;
}

// Legacy simple salary type
export interface SalarySlip {
  id?: string;
  employeeName: string;
  month: number;
  year: number;
  basicSalary: number;
  allowances: number;
  deductions: number;
  totalSalary: number;
}

// --- DASHBOARD ANALYTICS TYPES ---

export interface PerformerMetric {
  employeeId: string;
  name: string;
  avatarUrl?: string;
  avgScore: number;
}

export interface TrendMetric {
  label: string;
  value: number; // e.g. Average score
  trend: 'UP' | 'DOWN' | 'STABLE';
}

export interface DashboardAnalytics {
  topPerformers: PerformerMetric[];
  fohAverage: number;
  bohAverage: number;
  itemTrends: TrendMetric[];
}

// --- OWNER KPI TYPES ---

export interface TrendData {
  value: number;
  percentageChange: number; // e.g. 5.2 for +5.2%, -2.1 for -2.1%
  trend: 'UP' | 'DOWN' | 'STABLE';
}

export interface FinancialKPIs {
  totalRevenue: TrendData;
  netProfit: TrendData;
  foodCostPercentage: TrendData;
  laborCostPercentage: TrendData;
  chartData: { label: string, revenue: number, cost: number }[]; // For charts
}

export interface OperationalKPIs {
  tableTurnoverRate: TrendData;
  avgOrderValue: TrendData;
  alerts: string[]; // e.g., "Low Inventory: Chicken"
}

export interface HRKPIs {
  employeeTurnoverRate: TrendData;
  attendanceCompliance: number; // percentage
  topEmployees: PerformerMetric[];
}

export interface CustomerKPIs {
  csatScore: TrendData; // 1-5 scale
  reviewCount: number;
}

export interface MarketingKPIs {
  marketingRoi: TrendData; // Return on Ad Spend
  socialEngagement: TrendData;
}

export interface OwnerDashboardData {
  financial: FinancialKPIs;
  operational: OperationalKPIs;
  hr: HRKPIs;
  customer: CustomerKPIs;
  marketing: MarketingKPIs;
}


// --- SYSTEM ADMIN & IMPERSONATION TYPES ---

export interface AuditLog {
  id: string;
  action: string;
  performedBy: string; // User ID (Real Super Admin ID)
  impersonatingUser?: string; // If action was done while viewing as someone else
  targetEntity?: string;
  details: string;
  timestamp: string;
}

export interface SystemSetting {
  key: string;
  value: boolean | string | number;
  label: string;
  description: string;
}

export interface ImpersonationSession {
  isActive: boolean;
  realAdminId: string; // The Super Admin ID
  effectiveUserId: string; // The ID of the user being impersonated
  startedAt: string;
}

// --- MESSAGING TYPES ---
export enum MessageAudience {
  ALL_STAFF = 'ALL_STAFF',
  ALL_MANAGERS = 'ALL_MANAGERS',
  BUSINESS_OWNER = 'BUSINESS_OWNER',
  FOH_ONLY = 'FOH_ONLY',
  BOH_ONLY = 'BOH_ONLY',
}

export interface Message {
  id: string;
  senderId: string;
  senderName: string;
  senderAvatarUrl?: string;
  senderRole: UserRole;
  content: string;
  timestamp: string; // ISO String
  audience: MessageAudience;
  readBy: string[]; // Array of employee IDs who have read it
  senderArea: EmployeeArea;
}


// --- CONSTANTS FOR DAILY CHECKLISTS (PERFORMANCE EVAL) ---

export const CHECKLIST_ITEMS_GENERAL: ChecklistItemDef[] = [
  { key: 'gen_attendance', label: 'Kehadiran & Ketepatan Waktu', description: 'Datang tepat waktu, siap kerja sesuai jadwal', category: 'UMUM' },
  { key: 'gen_grooming', label: 'Kerapihan & Kebersihan Diri', description: 'Seragam bersih, rambut rapi, tidak berbau badan', category: 'UMUM' },
  { key: 'gen_attitude', label: 'Sikap & Etika Kerja', description: 'Sopan, ramah, saling menghormati', category: 'UMUM' },
  { key: 'gen_discipline', label: 'Disiplin & Tanggung Jawab', description: 'Menyelesaikan tugas tanpa disuruh berulang', category: 'UMUM' },
  { key: 'gen_teamwork', label: 'Kerja Sama Tim', description: 'Mau membantu rekan kerja, menjaga komunikasi baik', category: 'UMUM' },
];

export const CHECKLIST_ITEMS_KITCHEN: ChecklistItemDef[] = [
  { key: 'kit_cleanliness', label: 'Kerapihan Area Kerja', description: 'Meja kerja bersih, bahan tersusun rapi', category: 'KHUSUS' },
  { key: 'kit_speed', label: 'Kecepatan & Ketepatan Masak', description: 'Menyajikan tepat waktu sesuai SOP', category: 'KHUSUS' },
  { key: 'kit_quality', label: 'Kualitas & Konsistensi Rasa', description: 'Cita rasa stabil sesuai standar Pawon Salam', category: 'KHUSUS' },
  { key: 'kit_recipe', label: 'Pemahaman Resep & SOP', description: 'Mengikuti prosedur masak dan porsi dengan benar', category: 'KHUSUS' },
  { key: 'kit_comm', label: 'Kerjasama dengan Tim Waiter', description: 'Komunikatif saat ada pesanan ramai / revisi order', category: 'KHUSUS' },
];

export const CHECKLIST_ITEMS_WAITER: ChecklistItemDef[] = [
  { key: 'wai_speed', label: 'Kecepatan & Ketepatan Layanan', description: 'Pelayanan cepat dan sesuai pesanan', category: 'KHUSUS' },
  { key: 'wai_menu', label: 'Pengetahuan Menu', description: 'Menguasai menu, bisa memberi rekomendasi ke pelanggan', category: 'KHUSUS' },
  { key: 'wai_comm', label: 'Komunikasi dengan Pelanggan', description: 'Ramah, tidak gugup, responsif terhadap keluhan', category: 'KHUSUS' },
  { key: 'wai_cleanliness', label: 'Kebersihan Area Meja & Ruang Makan', description: 'Meja bersih, alat makan tertata', category: 'KHUSUS' },
  { key: 'wai_proactive', label: 'Proaktif & Inisiatif', description: 'Menyapa pelanggan, menawarkan bantuan tanpa disuruh', category: 'KHUSUS' },
];

// --- MONTHLY PERFORMANCE INDICATORS ---

export const FOH_INDICATORS: PerformanceIndicator[] = [
  { key: 'attitude', label: 'Attitude & Friendliness', category: EmployeeArea.FOH },
  { key: 'guest_comm', label: 'Guest Communication', category: EmployeeArea.FOH },
  { key: 'team_comm', label: 'Team Communication', category: EmployeeArea.FOH },
  { key: 'product_knowledge', label: 'Menu Knowledge', category: EmployeeArea.FOH },
  { key: 'service_speed', label: 'Service Speed', category: EmployeeArea.FOH },
  { key: 'accuracy', label: 'Order Accuracy', category: EmployeeArea.FOH },
  { key: 'complaints', label: 'Complaint Handling', category: EmployeeArea.FOH },
  { key: 'grooming', label: 'Appearance & Grooming', category: EmployeeArea.FOH },
  { key: 'sop', label: 'SOP Compliance', category: EmployeeArea.FOH },
  { key: 'cleanliness', label: 'Area Cleanliness', category: EmployeeArea.FOH },
  { key: 'initiative', label: 'Productivity/Initiative', category: EmployeeArea.FOH },
  { key: 'attendance', label: 'Attendance', category: EmployeeArea.FOH },
];

export const BOH_INDICATORS: PerformanceIndicator[] = [
  { key: 'food_quality', label: 'Food Quality/Taste', category: EmployeeArea.BOH },
  { key: 'speed', label: 'Production Speed', category: EmployeeArea.BOH },
  { key: 'recipe', label: 'Recipe Compliance', category: EmployeeArea.BOH },
  { key: 'hygiene', label: 'Personal Hygiene', category: EmployeeArea.BOH },
  { key: 'cleanliness', label: 'Kitchen Cleanliness', category: EmployeeArea.BOH },
  { key: 'equipment', label: 'Equipment Care', category: EmployeeArea.BOH },
  { key: 'ingredients', label: 'Ingredient Handling', category: EmployeeArea.BOH },
  { key: 'waste', label: 'Waste Control', category: EmployeeArea.BOH },
  { key: 'sop', label: 'SOP Compliance', category: EmployeeArea.BOH },
  { key: 'teamwork', label: 'Teamwork', category: EmployeeArea.BOH },
  { key: 'discipline', label: 'Shift Discipline', category: EmployeeArea.BOH },
  { key: 'safety', label: 'Safety Standards', category: EmployeeArea.BOH },
];

// --- DAILY JOBDESK CONSTANTS ---

export const JOBDESK_FOH_ITEMS: string[] = [
  "Menyapu area lantai 1, area lantai 2, dan seluruh tangga.",
  "Mengepel area lantai 1, area lantai 2, dan seluruh tangga.",
  "Membersihkan dan merapikan seluruh meja di area lantai 1 dan area lantai 2.",
  "Membersihkan kaca jendela dan partisi kaca di area lantai 1 dan area lantai 2.",
  "Menyiapkan dan membuat teh baru untuk operasional hari tersebut.",
  "Membersihkan dan menguras mesin es batu hingga higienis.",
  "Membersihkan dan merapikan area mini bar.",
  "Melipat dan menyiapkan kemasan take away.",
  "Mengecek stok seluruh aneka minuman (chiller, gudang, mini bar).",
  "Membersihkan bagian luar dan dalam kulkas di area lantai 1 dan area lantai 2 bila ada.",
  "Menata ulang dan merapikan minuman di dalam kulkas.",
  "Membersihkan dan mengecek kebersihan toilet/restroom secara berkala.",
  "Mencuci mobil dan motor operasional restoran.",
  "Membersihkan dan merapikan seluruh area lantai 2 (meja, kursi, lantai).",
  "Menyalakan dan mengatur musik resto selama jam operasional.",
  "Mengajak pelanggan untuk melakukan scan Google Review setelah selesai makan.",
  "Membuat laporan omzet harian dan mengunggah foto meteran listrik sesuai prosedur.",
  "Menyiapkan sendok, garpu, dan perlengkapan makan lainnya untuk pelanggan.",
  "Melakukan stok opname berkala untuk seluruh item FOH (minuman, kemasan, perlengkapan servis)."
];

export const JOBDESK_BOH_ITEMS: string[] = [
  "Memasak nasi sesuai kebutuhan operasional.",
  "Merebus mie hingga siap saji sesuai standar.",
  "Merebus bihun hingga siap saji sesuai standar.",
  "Memanaskan dan menyiapkan komponen berikut sebelum operasional: nasi, kuah kaldu ayam dan sapi, kuah rawon, kuah pindang, kuah soto, sambal, bihun, dan ayam suwir.",
  "Mencuci piring, gelas, dan seluruh peralatan makan/masak yang digunakan.",
  "Mengeringkan (lap kering) seluruh peralatan yang sudah dicuci dan menyusunnya kembali.",
  "Membersihkan area kompor, termasuk permukaan dan sekelilingnya.",
  "Membersihkan meja servis dan area plating.",
  "Membersihkan isi kulkas (membuang bahan yang rusak, merapikan penyimpanan).",
  "Merapikan dan membersihkan rak penyimpanan bahan dan peralatan.",
  "Memotong sayuran (kol, sawi, daun bawang, seledri, timun) sesuai standar potongan.",
  "Membuat acar untuk kebutuhan operasional.",
  "Menggoreng kerupuk dan emping sesuai kebutuhan.",
  "Membungkus kerupuk dan emping ke dalam kemasan saji.",
  "Mengupas bawang dan cabai untuk persiapan bumbu.",
  "Menyapu dan mengepel lantai area dapur.",
  "Mencuci lap kotor dan menggantinya dengan lap bersih.",
  "Membeli galon air sesuai kebutuhan dan instruksi.",
  "Memasang gas elpiji dengan aman dan sesuai prosedur keselamatan.",
  "Memasang galon air ke dispenser dengan benar.",
  "Melakukan belanja kecil ke Indomaret sesuai daftar kebutuhan dapur.",
  "Melakukan stok opname berkala untuk seluruh bahan baku dan perlengkapan dapur BOH."
];

export interface PayrollData {
  month: string;
  employeeName: string;
  nik: string;
  position: string;
  basicSalary: number;
  allowances: number;
  positionAllowance: number;
  attendanceDays: number;
  overtime: number;
  tax: number;
  otherDeductions: number;
}

// --- GAMIFICATION TYPES (Employee Engagement System) ---

export type BadgeType = 'PUNCTUAL_HERO' | 'OVERTIME_CHAMPION' | 'PERFECT_MONTH' | 'STREAK_WARRIOR';
export type BadgeColor = 'gold' | 'silver' | 'bronze';

export interface EmployeePoints {
  id: string;
  employeeId: string;
  points: number; // Current balance
  level: number;
  totalEarnedPoints: number; // Lifetime total
  pointsThisMonth: number;
  attendanceStreak: number; // Consecutive days on-time
  overtimeCount: number;
  perfectMonthCount: number;
  lastPointEarnedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface Badge {
  id: string;
  employeeId: string;
  badgeType: BadgeType;
  badgeName: string;
  badgeIcon: string; // Emoji or icon name
  badgeColor: BadgeColor;
  earnedAt: string;
  requirementMet: string; // e.g., "100 on-time attendances"
}

export interface PointTransaction {
  id: string;
  employeeId: string;
  pointsDelta: number; // +10, -5, etc.
  transactionType: 'ATTENDANCE' | 'OVERTIME' | 'PENALTY' | 'BONUS' | 'REDEMPTION';
  reason: string;
  referenceType?: string; // 'ATTENDANCE_LOG', 'OVERTIME_REQUEST'
  referenceId?: string;
  createdAt: string;
  createdBy?: string; // Admin who triggered
}

export interface LevelTier {
  level: number;
  minPoints: number;
  title: string; // 'Rookie', 'Pro', 'Master', etc.
  color: string; // Hex color
}

export const LEVEL_THRESHOLDS: LevelTier[] = [
  { level: 1, minPoints: 0, title: 'Rookie', color: '#94a3b8' },
  { level: 2, minPoints: 100, title: 'Regular', color: '#3b82f6' },
  { level: 3, minPoints: 300, title: 'Pro', color: '#8b5cf6' },
  { level: 4, minPoints: 600, title: 'Expert', color: '#f59e0b' },
  { level: 5, minPoints: 1000, title: 'Master', color: '#ef4444' },
  { level: 6, minPoints: 1500, title: 'Legend', color: '#fbbf24' }
];

// --- SMART ROSTER / LABOR COST TYPES ---

export type AlertLevel = 'GREEN' | 'YELLOW' | 'RED';

export interface DailyLaborMetrics {
  id: string;
  date: string; // YYYY-MM-DD
  outlet: string;
  totalStaffScheduled: number;
  totalStaffAttendance: number;
  estimatedDailyLaborCost: number;
  dailyRevenue: number;
  laborCostPercentage: number; // (Labor Cost / Revenue) * 100
  revenuePerEmployee: number;
  efficiencyScore: number;
  isOverstaffed: boolean;
  alertLevel: AlertLevel;
  createdAt: string;
}

export interface LaborCostSnapshot {
  laborPercentage: number;
  alertLevel: AlertLevel;
  estimatedLaborCost: number;
  dailyRevenue: number;
  totalStaffCount: number;
  revenuePerEmployee: number;
}
